// Generated by LazyStack - modifications will be overwritten
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace PetStoreCLI
{
    public partial class Startup
    {
        public void ConfigureSvcs(IServiceCollection services)
        {

        }
    }
}